[package]
name = "dlp_printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
slint = "1.5.1"
zip = "0.6.6"

